# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 59b0efbaaaffebc60ef722c2971e67829f036adf2904ae3a615539644f0575eab94048800c55cec182a99e6c10947aec11e425fe4c71eb833821088fc8642ee7

test:
  secret_key_base: 422ae992bc193a957665f8ff941d65e9ddf03d03c3f3380b0ae11f1bd79b71d33be9d77677e43607d4c2867ef3390a53a09b5f31677704ec0233bfacfb466d5c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
